interface ZIF_CUSTOMER_MASTER_DATA1_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ROOT,
 CREATE_ROOT                    TYPE /BOBF/ACT_KEY VALUE '1C4D709BFCA81EEA9A8DB6F74A3BCB63',
 DELETE_ROOT                    TYPE /BOBF/ACT_KEY VALUE '1C4D709BFCA81EEA9A8DB6F74A3C4B63',
 LOCK_ROOT                      TYPE /BOBF/ACT_KEY VALUE '1C4D709BFCA81EEA9A8DB6D7A81B8B63',
 SAVE_ROOT                      TYPE /BOBF/ACT_KEY VALUE '1C4D709BFCA81EEA9A8DB6F74A3CCB63',
 UNLOCK_ROOT                    TYPE /BOBF/ACT_KEY VALUE '1C4D709BFCA81EEA9A8DB6D7A81BCB63',
 UPDATE_ROOT                    TYPE /BOBF/ACT_KEY VALUE '1C4D709BFCA81EEA9A8DB6F74A3C0B63',
 VALIDATE_ROOT                  TYPE /BOBF/ACT_KEY VALUE '1C4D709BFCA81EEA9A8DB6F74A3C8B63',
      END OF ROOT,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ROOT,
        BEGIN OF LOCK_ROOT,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF LOCK_ROOT,
        BEGIN OF UNLOCK_ROOT,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF UNLOCK_ROOT,
      END OF ROOT,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ROOT,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '1C4D709BFCA81EEA9A8DB6D7A81B6B63',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '1C4D709BFCA81EEA9A8DB6D7A81B2B63',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '1C4D709BFCA81EEA9A8DB6D7A81C2B63',
      END OF ROOT,
      BEGIN OF ROOT_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '1C4D709BFCA81EEA9A8DB6F74A3D2B63',
      END OF ROOT_LOCK,
      BEGIN OF ROOT_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '1C4D709BFCA81EEA9A8DB6F74A3D0B63',
      END OF ROOT_MESSAGE,
      BEGIN OF ROOT_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '1C4D709BFCA81EEA9A8DB6F74A3D4B63',
      END OF ROOT_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ROOT,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ROOT,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '1C4D709BFCA81EEA9A8DB6D7A81A8B63' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'Z_CUSTOMER_MASTER_DATA' .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ROOT                           TYPE /BOBF/OBM_NODE_KEY VALUE '1C4D709BFCA81EEA9A8DB6D7A81ACB63',
 ROOT_LOCK                      TYPE /BOBF/OBM_NODE_KEY VALUE '1C4D709BFCA81EEA9A8DB6D7A81B4B63',
 ROOT_MESSAGE                   TYPE /BOBF/OBM_NODE_KEY VALUE '1C4D709BFCA81EEA9A8DB6D7A81B0B63',
 ROOT_PROPERTY                  TYPE /BOBF/OBM_NODE_KEY VALUE '1C4D709BFCA81EEA9A8DB6D7A81C0B63',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ROOT,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  KUNNR                          TYPE STRING VALUE 'KUNNR',
  NAME1                          TYPE STRING VALUE 'NAME1',
  LAND1                          TYPE STRING VALUE 'LAND1',
  REGIO                          TYPE STRING VALUE 'REGIO',
  TRANSIENT_NODE_DATA            TYPE STRING VALUE 'TRANSIENT_NODE_DATA',
  KUNNR_TS                       TYPE STRING VALUE 'KUNNR_TS',
  NAME1_TS                       TYPE STRING VALUE 'NAME1_TS',
  LAND1_TS                       TYPE STRING VALUE 'LAND1_TS',
  REGIO_TS                       TYPE STRING VALUE 'REGIO_TS',
      END OF ROOT,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ROOT,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '1C4D709BFCA81EEA9A8DB6D7A81AEB63',
      END OF ROOT,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_QUERY,
      BEGIN OF ROOT,
 QUERY_BY_ATTRIBUTES            TYPE /BOBF/OBM_QUERY_KEY VALUE '1C4D709BFCA81EEA9AB87736B933CB78',
 SELECT_ALL                     TYPE /BOBF/OBM_QUERY_KEY VALUE '1C4D709BFCA81EEA9A8DD3338E4B6B63',
 SELECT_BY_ELEMENTS             TYPE /BOBF/OBM_QUERY_KEY VALUE '1C4D709BFCA81EEA9A8DD359AA67AB63',
      END OF ROOT,
    END OF SC_QUERY .
  constants:
    BEGIN OF SC_QUERY_ATTRIBUTE,
      BEGIN OF ROOT,
        BEGIN OF QUERY_BY_ATTRIBUTES,
 KEY                            TYPE STRING VALUE 'KEY',
 PARENT_KEY                     TYPE STRING VALUE 'PARENT_KEY',
 ROOT_KEY                       TYPE STRING VALUE 'ROOT_KEY',
 NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
 KUNNR                          TYPE STRING VALUE 'KUNNR',
 NAME1                          TYPE STRING VALUE 'NAME1',
 LAND1                          TYPE STRING VALUE 'LAND1',
 REGIO                          TYPE STRING VALUE 'REGIO',
 TRANSIENT_NODE_DATA            TYPE STRING VALUE 'TRANSIENT_NODE_DATA',
 KUNNR_TS                       TYPE STRING VALUE 'KUNNR_TS',
 NAME1_TS                       TYPE STRING VALUE 'NAME1_TS',
 LAND1_TS                       TYPE STRING VALUE 'LAND1_TS',
 REGIO_TS                       TYPE STRING VALUE 'REGIO_TS',
        END OF QUERY_BY_ATTRIBUTES,
        BEGIN OF SELECT_BY_ELEMENTS,
 KEY                            TYPE STRING VALUE 'KEY',
 PARENT_KEY                     TYPE STRING VALUE 'PARENT_KEY',
 ROOT_KEY                       TYPE STRING VALUE 'ROOT_KEY',
 NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
 KUNNR                          TYPE STRING VALUE 'KUNNR',
 NAME1                          TYPE STRING VALUE 'NAME1',
 LAND1                          TYPE STRING VALUE 'LAND1',
 REGIO                          TYPE STRING VALUE 'REGIO',
 TRANSIENT_NODE_DATA            TYPE STRING VALUE 'TRANSIENT_NODE_DATA',
 KUNNR_TS                       TYPE STRING VALUE 'KUNNR_TS',
 NAME1_TS                       TYPE STRING VALUE 'NAME1_TS',
 LAND1_TS                       TYPE STRING VALUE 'LAND1_TS',
 REGIO_TS                       TYPE STRING VALUE 'REGIO_TS',
        END OF SELECT_BY_ELEMENTS,
      END OF ROOT,
    END OF SC_QUERY_ATTRIBUTE .
endinterface.
