sap.ui.jsview("publicholidays.publicHolidays", {                                                                                                                                                                                                               
                                                                                                                                                                                                                                                               
	/** Specifies the Controller belonging to this View.&nbsp;                                                                                                                                                                                                    
	* In the case that it is not implemented, or that "null" is returned, this View does not have a Controller.                                                                                                                                                   
	* @memberOf publicholidays.publicHolidays                                                                                                                                                                                                                     
	*/&nbsp;                                                                                                                                                                                                                                                      
	getControllerName : function() {                                                                                                                                                                                                                              
		return "publicholidays.publicHolidays";                                                                                                                                                                                                                      
	},                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                               
	/** Is initially called once after the Controller has been instantiated. It is the place where the UI is constructed.&nbsp;                                                                                                                                   
	* Since the Controller is given to this method, its event handlers can be attached right away.&nbsp;                                                                                                                                                          
	* @memberOf publicholidays.publicHolidays                                                                                                                                                                                                                     
	*/&nbsp;                                                                                                                                                                                                                                                      
	createContent : function(oController) {                                                                                                                                                                                                                       
		// load table module, alternatively add sap.ui.table to the central bootstrap - see AAAA                                                                                                                                                                     
		jQuery.sap.require("sap.ui.table.Table");                                                                                                                                                                                                                    
		                                                                                                                                                                                                                                                             
		// create table control with properties                                                                                                                                                                                                                      
		var oTable = new sap.ui.table.Table(                                                                                                                                                                                                                         
			{                                                                                                                                                                                                                                                           
				width : "100%",                                                                                                                                                                                                                                            
				rowHeight : 50,                                                                                                                                                                                                                                            
				title : "List of Holidays",                                                                                                                                                                                                                                
				selectionMode : sap.ui.table.SelectionMode.None                                                                                                                                                                                                            
			}                                                                                                                                                                                                                                                           
		);                                                                                                                                                                                                                                                           
		                                                                                                                                                                                                                                                             
		// define the columns, which should be displayed                                                                                                                                                                                                             
		// holiday date                                                                                                                                                                                                                                              
		oTable.addColumn(                                                                                                                                                                                                                                            
			new sap.ui.table.Column(                                                                                                                                                                                                                                    
				{                                                                                                                                                                                                                                                          
					label : new sap.ui.commons.Label (                                                                                                                                                                                                                        
						{                                                                                                                                                                                                                                                        
							text : "Date"                                                                                                                                                                                                                                           
						}                                                                                                                                                                                                                                                        
					),                                                                                                                                                                                                                                                        
					template : new sap.ui.commons.TextView (                                                                                                                                                                                                                  
						{                                                                                                                                                                                                                                                        
							text : "{date}"                                                                                                                                                                                                                                         
						}                                                                                                                                                                                                                                                        
					),                                                                                                                                                                                                                                                        
					//template : sap.ui.commons.TextView().bindProperty("text", "date") ,                                                                                                                                                                                     
					//template : new sap.ui.commons.TextView().bindText("date") ,                                                                                                                                                                                             
					sortProperty : "Date"                                                                                                                                                                                                                                     
				}                                                                                                                                                                                                                                                          
			)                                                                                                                                                                                                                                                           
		);                                                                                                                                                                                                                                                           
		// holiday local name                                                                                                                                                                                                                                        
		oTable.addColumn(                                                                                                                                                                                                                                            
			new sap.ui.table.Column(                                                                                                                                                                                                                                    
				{                                                                                                                                                                                                                                                          
					label : new sap.ui.commons.Label (                                                                                                                                                                                                                        
						{                                                                                                                                                                                                                                                        
							text : "Local name"                                                                                                                                                                                                                                     
						}                                                                                                                                                                                                                                                        
					),                                                                                                                                                                                                                                                        
					template : new sap.ui.commons.TextView (                                                                                                                                                                                                                  
						{                                                                                                                                                                                                                                                        
							text : "{localName}"                                                                                                                                                                                                                                    
						}                                                                                                                                                                                                                                                        
					),                                                                                                                                                                                                                                                        
					//sortProperty : "Date"                                                                                                                                                                                                                                   
				}                                                                                                                                                                                                                                                          
			)                                                                                                                                                                                                                                                           
		);                                                                                                                                                                                                                                                           
		// holiday english name                                                                                                                                                                                                                                      
		oTable.addColumn(                                                                                                                                                                                                                                            
			new sap.ui.table.Column(                                                                                                                                                                                                                                    
				{                                                                                                                                                                                                                                                          
					label : new sap.ui.commons.Label (                                                                                                                                                                                                                        
						{                                                                                                                                                                                                                                                        
							text : "English name"                                                                                                                                                                                                                                   
						}                                                                                                                                                                                                                                                        
					),                                                                                                                                                                                                                                                        
					template : new sap.ui.commons.TextView (                                                                                                                                                                                                                  
						{                                                                                                                                                                                                                                                        
							text : "{englishName}"                                                                                                                                                                                                                                  
						}                                                                                                                                                                                                                                                        
					),                                                                                                                                                                                                                                                        
					//sortProperty : "Date"                                                                                                                                                                                                                                   
				}                                                                                                                                                                                                                                                          
			)                                                                                                                                                                                                                                                           
		);                                                                                                                                                                                                                                                           
		// holiday note                                                                                                                                                                                                                                              
		oTable.addColumn(                                                                                                                                                                                                                                            
			new sap.ui.table.Column(                                                                                                                                                                                                                                    
				{                                                                                                                                                                                                                                                          
					label : new sap.ui.commons.Label (                                                                                                                                                                                                                        
						{                                                                                                                                                                                                                                                        
							text : "Note"                                                                                                                                                                                                                                           
						}                                                                                                                                                                                                                                                        
					),                                                                                                                                                                                                                                                        
					template : new sap.ui.commons.TextView (                                                                                                                                                                                                                  
						{                                                                                                                                                                                                                                                        
							text : "{note}"                                                                                                                                                                                                                                         
						}                                                                                                                                                                                                                                                        
					),                                                                                                                                                                                                                                                        
					//sortProperty : "Date"                                                                                                                                                                                                                                   
				}                                                                                                                                                                                                                                                          
			)                                                                                                                                                                                                                                                           
		);                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                               
		                                                                                                                                                                                                                                                             
		//bind content                                                                                                                                                                                                                                               
		oTable.bindRows("/modelData");                                                                                                                                                                                                                               
		return oTable;                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                               
	}	//createContenct                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                               
});                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                               