sap.ui.jsview("sapui5_using_abap_channels.OpenSalesOrders", {                                                                                                                                                                                                  
                                                                                                                                                                                                                                                               
	/** Specifies the Controller belonging to this View.&nbsp;                                                                                                                                                                                                    
	* In the case that it is not implemented, or that "null" is returned, this View does not have a Controller.                                                                                                                                                   
	* @memberOf sapui5_using_abap_channels.OpenSalesOrders                                                                                                                                                                                                        
	*/&nbsp;                                                                                                                                                                                                                                                      
	getControllerName : function() {                                                                                                                                                                                                                              
		return "sapui5_using_abap_channels.OpenSalesOrders";                                                                                                                                                                                                         
	},                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                               
	/** Is initially called once after the Controller has been instantiated. It is the place where the UI is constructed.&nbsp;                                                                                                                                   
	* Since the Controller is given to this method, its event handlers can be attached right away.&nbsp;                                                                                                                                                          
	* @memberOf sapui5_using_abap_channels.OpenSalesOrders                                                                                                                                                                                                        
	*/&nbsp;                                                                                                                                                                                                                                                      
	createContent : function(oController) {                                                                                                                                                                                                                       
		// initialize chart dataset                                                                                                                                                                                                                                  
		oDunningAnalysisChartDataset = new sap.viz.ui5.data.FlattenedDataset(                                                                                                                                                                                        
			"idDunningAnalysisChartDataset", {                                                                                                                                                                                                                          
				dimensions : [ {                                                                                                                                                                                                                                           
					axis : 1,                                                                                                                                                                                                                                                 
					name : "Dunning Level",                                                                                                                                                                                                                                   
					value : "{DunningLevel}"                                                                                                                                                                                                                                  
				} ],                                                                                                                                                                                                                                                       
				measures : [ {                                                                                                                                                                                                                                             
					name : "Sales Orders",                                                                                                                                                                                                                                    
					value : "{NoSalesOrders}"                                                                                                                                                                                                                                 
				} ],                                                                                                                                                                                                                                                       
				data : {                                                                                                                                                                                                                                                   
					path : "/modelData/DunningLevelDetails"                                                                                                                                                                                                                   
				}                                                                                                                                                                                                                                                          
		});                                                                                                                                                                                                                                                          
		                                                                                                                                                                                                                                                             
		// Initialize donut chart                                                                                                                                                                                                                                    
		oDunningAnalysisChart = new sap.viz.ui5.Donut("idDunningAnalysisChart",                                                                                                                                                                                      
			{                                                                                                                                                                                                                                                           
				title : {                                                                                                                                                                                                                                                  
					visible : true,                                                                                                                                                                                                                                           
					text : "Sales Orders by Dunning Level"                                                                                                                                                                                                                    
				},                                                                                                                                                                                                                                                         
				dataset : oDunningAnalysisChartDataset                                                                                                                                                                                                                     
			});                                                                                                                                                                                                                                                         
		oDunningAnalysisChart.setModel(sap.ui.getCore().getModel());                                                                                                                                                                                                 
		                                                                                                                                                                                                                                                             
		// initialize page                                                                                                                                                                                                                                           
		oDunningAnalysisPage = new sap.m.Page({                                                                                                                                                                                                                      
			title : "Dunning Analysis",                                                                                                                                                                                                                                 
			content : [ oDunningAnalysisChart ] // add the chart to the page                                                                                                                                                                                            
		});                                                                                                                                                                                                                                                          
		                                                                                                                                                                                                                                                             
		// return the object from createContent function                                                                                                                                                                                                             
		return oDunningAnalysisPage;                                                                                                                                                                                                                                 
	}                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                               
});                                                                                                                                                                                                                                                            